version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: gumtree-mb
    working_dir: /works
    tty: true
    command: tail -f /dev/null
    ports:
      - 4567:4567
    volumes:
      - type: bind
        source: ./
        target: /works